services:
  web:
    build:
      context: .
      target: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  php:
    build:
      context: .
      target: php
    volumes:
      - .:/var/www/html

  apache:
    build:
      context: .
      target: apache
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret